import "@/styles/globals.css";


import { type Metadata } from "next";
import { Geist } from "next/font/google";

import SidebarWithLogin from "./components/SidebarWithLogin";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "GetMate",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <SessionProvider>
          <div className="min-h-screen flex bg-[#F0F0DB] text-[#30364F] font-mono">
            <SidebarWithLogin />
            <main className="flex-1 p-8">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
